/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/Ingredient`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/detailsController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/FavoriteRecipesController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/LoginController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/useRecipeListController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/SignUpController`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../controllers/Ingredient`; params?: Router.UnknownOutputParams; } | { pathname: `/../controllers/detailsController`; params?: Router.UnknownOutputParams; } | { pathname: `/../controllers/FavoriteRecipesController`; params?: Router.UnknownOutputParams; } | { pathname: `/../controllers/LoginController`; params?: Router.UnknownOutputParams; } | { pathname: `/../controllers/useRecipeListController`; params?: Router.UnknownOutputParams; } | { pathname: `/../controllers/SignUpController`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../controllers/Ingredient${`?${string}` | `#${string}` | ''}` | `/../controllers/detailsController${`?${string}` | `#${string}` | ''}` | `/../controllers/FavoriteRecipesController${`?${string}` | `#${string}` | ''}` | `/../controllers/LoginController${`?${string}` | `#${string}` | ''}` | `/../controllers/useRecipeListController${`?${string}` | `#${string}` | ''}` | `/../controllers/SignUpController${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/Ingredient`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/detailsController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/FavoriteRecipesController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/LoginController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/useRecipeListController`; params?: Router.UnknownInputParams; } | { pathname: `/../controllers/SignUpController`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
